name: xunit-test-metrics-action CI

on: [push, workflow_dispatch]

jobs:
  documentation:
    name: Attach Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: 'false'

      - name: Attach Documentation
        run: cat .github/workflows/README.md >> $GITHUB_STEP_SUMMARY

  nodeJS:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [6, 8, 10, 12, 14, 16, 18]

    name: Build and Test - nodeJS v${{ matrix.node-version }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Setup nodeJS v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Initialize Project
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
